# Generated by Django 4.2.4 on 2023-08-02 07:51

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.models.access_policy


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0108_task_versions"),
        ("container", "0036_containerpushrepository_pending_blobs_manifests"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerPullThroughDistribution",
            fields=[
                (
                    "distribution_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.distribution",
                    ),
                ),
                (
                    "private",
                    models.BooleanField(
                        default=False,
                        help_text="Restrict pull access to explicitly authorized users. Defaults to unrestricted pull access.",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
            bases=("core.distribution", pulpcore.app.models.access_policy.AutoAddObjPermsMixin),
        ),
        migrations.CreateModel(
            name="ContainerPullThroughRemote",
            fields=[
                (
                    "remote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.remote",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
            bases=("core.remote", pulpcore.app.models.access_policy.AutoAddObjPermsMixin),
        ),
        migrations.AddField(
            model_name="containerrepository",
            name="pending_blobs",
            field=models.ManyToManyField(related_name="pending_blobs", to="container.blob"),
        ),
        migrations.AddField(
            model_name="containerrepository",
            name="pending_manifests",
            field=models.ManyToManyField(to="container.manifest"),
        ),
        migrations.AddField(
            model_name="containerrepository",
            name="pending_tags",
            field=models.ManyToManyField(to="container.tag"),
        ),
        migrations.AddField(
            model_name="containerrepository",
            name="remaining_blobs",
            field=models.ManyToManyField(related_name="remaining_blobs", to="container.blob"),
        ),
        migrations.AddField(
            model_name="containerdistribution",
            name="pull_through_distribution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to="container.containerpullthroughdistribution",
            ),
        ),
    ]
